name: Deploy Logic App Standard

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Logic App using Bicep or ARM
        run: |
          az deployment group create \
            --resource-group MyResourceGroup \
            --template-file azuredeploy.bicep \
            --parameters @parameters.json

      - name: Deploy Logic App using ZIP (for function-based apps)
        run: |
          zip -r logicapp.zip .
          az webapp deployment source config-zip \
            --resource-group MyResourceGroup \
            --name MyLogicApp \
            --src logicapp.zip
